name: email_validator
version:  2.1.1

homepage: https://github.com/fredeil/email-validator.dart
description: A simple (but correct) dart class for validating email addresses

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.8
